### ISSUE TITLE
Jenkins Integrated Reporting plugin

### ISSUE THREAD

**Issue by spookyvale** [STAMP-project/docs-forum#12]
I just released the initial version of a Jenkins plugin to visualize and aggregate Descartes Reports in Jenkins.
You can have a look at it at [https://github.com/STAMP-project/jenkins-stamp-report-plugin]
I would like for you to send some feedback / requirements on the type of information most relevant for you (metrics, aggregated results across builds, etc) so to enhance the plugin.

Also, if it is also interesting for the project, I think it would be nice to integrate in the plugin also Dspot result reports (and possibly others).

**Comment by vmassol** [comment]
Thanks @spookyvale Would be awesome if you could add some screenshots to https://github.com/STAMP-project/jenkins-stamp-report-plugin so that we can see how it looks like inside Jenkins :)

**Comment by vmassol** [comment]
Very nice! Well done
