### ISSUE TITLE
fill the "Publication" page on stamp.ow2.org 

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/docs-forum#3]
point raised by @cedricth during his talk

**Comment by azaidman** [comment]
I've just updated the TU Delft publications on https://stamp.ow2.org/bin/view/main/publications

Did I misunderstand and do you want it elsewhere?

**Comment by monperrus** [comment]
thanks a lot @azaidman 

you're right. renamed the issue to "fill the page" :-)

**Comment by monperrus** [comment]
added "Correctness Attraction: A Study of Stability of Software Behavior Under Runtime Perturbation" by @danglotb in EMSE
