### ISSUE TITLE
Please add Nicola Bertazzo to STAMP organization

### ISSUE THREAD

**Issue by danzone** [STAMP-project/docs-forum#9]
Dear all, could you please add Nicola Bertazzo (@nicolabertazzo) to STAMP organization, in order to assign issues to him?

**Comment by CaelInria** [comment]
Done :-)

**Comment by danzone** [comment]
Hi Caroline, I can't assign issue https://github.com/STAMP-project/dspot/issues/296 to Nicola: when I try to assign it, Nicola isn't in the assignable users list.

**Comment by danzone** [comment]
OK solved, Nicola has joined the project, I could assign it the issue. Thanks!
